# Generated by Django 5.1.4 on 2025-06-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True,
                default=1,
                help_text="Email for communication and invoices.",
                max_length=254,
                verbose_name="Email Address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplier",
            name="notes",
            field=models.TextField(
                blank=True,
                default=1,
                help_text="Additional remarks or information about the supplier.",
                verbose_name="Notes",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="supplier",
            name="website",
            field=models.URLField(
                blank=True,
                default=1,
                help_text="Official website of the supplier, if any.",
                verbose_name="Website",
            ),
            preserve_default=False,
        ),
    ]
