# Generated by Django 5.1.4 on 2024-12-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("email",),
                name="unique_email_active_user",
            ),
        ),
    ]
