# Generated by Django 5.1.4 on 2025-05-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_unique_email_active_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="auth_provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribed_newsletter",
        ),
    ]
