# Generated by Django 5.2 on 2026-05-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "ordering": (
                    "permission_category__main_module",
                    "permission_category",
                    "id",
                ),
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("-id",),
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelOptions(
            name="useraccountverification",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="userforgetpasswordrequest",
            options={"ordering": ("-id",)},
        ),
    ]
