# Generated by Django 5.1.4 on 2025-06-02 13:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Optional barcode or EAN for scanning.",
                max_length=255,
                verbose_name="Barcode Code",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_alert_qty",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Quantity for Low Stock Alert",
                verbose_name="Stock Alert Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Category to which this product belongs.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_products",
                to="catalog.productcategory",
                verbose_name="Category",
            ),
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the unit, e.g., Kilogram, Piece.",
                        max_length=50,
                        unique=True,
                        verbose_name="Unit Name",
                    ),
                ),
                (
                    "short_form",
                    models.CharField(
                        help_text="Abbreviated form, e.g., kg, pcs.",
                        max_length=20,
                        unique=True,
                        verbose_name="Short Form",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Unit",
                "verbose_name_plural": "Product Units",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.ForeignKey(
                default=1,
                help_text="Unit in which this product is calculated.",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.productunit",
                verbose_name="Unit",
            ),
            preserve_default=False,
        ),
    ]
