# Generated by Django 5.2 on 2026-05-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TenantProfile",
        ),
    ]
