# Generated by Django 5.2 on 2026-05-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_delete_tenantprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
            },
        ),
    ]
