# Generated by Django 4.2 on 2024-05-25 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="is_seen",
            field=models.BooleanField(
                default=False,
                help_text="Is comment seen by admin.",
                verbose_name="Is seen",
            ),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="seen_by",
            field=models.ForeignKey(
                help_text="The user who mark the comment seen.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_seen_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="seen by",
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="name",
            field=models.CharField(
                help_text="The name as it appears on your site.",
                max_length=50,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
