# Generated by Django 4.2 on 2024-09-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_postcomment_is_seen_postcomment_seen_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcomment",
            name="seen_by",
            field=models.ForeignKey(
                help_text="The admin user who mark the comment seen.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_seen_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="seen by",
            ),
        ),
    ]
