# Generated by Django 4.2 on 2024-11-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postcomment_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PASSWORD-PROTECTED', 'Password protected')], help_text='Determines who can see this post. Public posts are visible to everyone, private posts are only visible to the author, and password-protected posts require a password to access.', max_length=20),
        ),
    ]
