# Generated by Django 5.1.4 on 2025-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_updated_by_postcategory_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcategory",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name.Lowercase with letters, numbers, and hyphens.",
                max_length=55,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="posttag",
            name="slug",
            field=models.SlugField(
                help_text="URL-friendly version of the name.Lowercase with letters, numbers, and hyphens.",
                max_length=55,
                unique=True,
            ),
        ),
    ]
