# Generated by Django 5.1.4 on 2025-06-06 17:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import src.libs.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_barcode_product_stock_alert_qty_and_more"),
        ("core", "0005_additionalchargetype_updated_by_and_more"),
        ("store", "0001_initial"),
        ("supplier", "0002_alter_supplier_email_alter_supplier_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[("PURCHASE", "Purchase"), ("RETURN", "Return")],
                        db_index=True,
                        help_text="Type of purchase (e.g., purchase, return).",
                        max_length=30,
                        verbose_name="Purchase Type",
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CREDIT", "Credit")],
                        help_text="Payment method used for this purchase.",
                        max_length=10,
                        verbose_name="Payment Type",
                    ),
                ),
                ("prefix", models.CharField(help_text="Prefix like: PU", max_length=3)),
                (
                    "purchase_no",
                    models.PositiveIntegerField(
                        help_text="Sequential number for tracking the purchase.",
                        verbose_name="Purchase Number",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall discount rate applied to the purchase.",
                        max_digits=5,
                        verbose_name="Discount Rate (%)",
                    ),
                ),
                (
                    "total_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total Discount Amount",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Tax Rate (%)"
                    ),
                ),
                (
                    "total_tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Tax Amount"
                    ),
                ),
                (
                    "sub_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Grand Total"
                    ),
                ),
                (
                    "round_off_grand_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Round Off Amount"
                    ),
                ),
                (
                    "bill_no",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bill Number"
                    ),
                ),
                (
                    "bill_date",
                    models.DateField(blank=True, null=True, verbose_name="Bill Date"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date to pay if purchase is in credit.",
                        null=True,
                        verbose_name="Due Date",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notes"),
                ),
                (
                    "show_notes_on_invoice",
                    models.BooleanField(
                        default=False,
                        help_text="Decides whether to show notes on invoice print.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ref_purchase_main",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the original purchase in case of returns or corrections.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.purchase",
                        verbose_name="Reference Purchase",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="Store where purchase is stored or received.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_purchases",
                        to="store.store",
                        verbose_name="Store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Supplier from whom the purchase was made.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_purchases",
                        to="supplier.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseAdditionalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Charge Amount"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        help_text="Date when this payment was done.",
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, max_length=50, verbose_name="Remarks"),
                ),
                (
                    "charge_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.additionalchargetype",
                        verbose_name="Charge Type",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additional_charges",
                        to="purchase.purchase",
                        verbose_name="Purchase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Additional Charge",
                "verbose_name_plural": "Additional Charges",
            },
        ),
        migrations.CreateModel(
            name="PurchaseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Attachment Title"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to="",
                        validators=[src.libs.validators.validate_file_extension],
                        verbose_name="Attachment File",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to="purchase.purchase",
                        verbose_name="Purchase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Attachment",
                "verbose_name_plural": "Purchase Attachments",
            },
        ),
        migrations.CreateModel(
            name="PurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Purchase Cost"
                    ),
                ),
                (
                    "min_sale_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Minimum Selling Price",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Tax Rate (%)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tax Amount"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Discount Rate (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Discount Amount",
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Gross Amount"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Amount"
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True,
                        help_text="Batch number for tracking purposes.",
                        max_length=50,
                        verbose_name="Batch Number",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date for the product, if applicable.",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                (
                    "track_serial",
                    models.BooleanField(
                        default=False, verbose_name="Track Serial/IMEI"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Remarks"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_details",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "purchase_main",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to="purchase.purchase",
                        verbose_name="Purchase Main",
                    ),
                ),
                (
                    "ref_purchase_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.purchasedetail",
                        verbose_name="Reference Purchase Detail",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Detail",
                "verbose_name_plural": "Purchase Details",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Payment Amount"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, max_length=50, verbose_name="Remarks"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.paymentmethod",
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_details",
                        to="purchase.purchase",
                        verbose_name="Purchase",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Payment Detail",
                "verbose_name_plural": "Purchase Payment Details",
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("PAYMENT", "Payment"), ("RETURN", "Return")],
                        help_text="Type of payment, e.g., payment, return",
                        max_length=20,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "payment_no",
                    models.CharField(
                        blank=True,
                        help_text="System-generated",
                        max_length=20,
                        verbose_name="Payment Number",
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        help_text="Receipt number provided to the supplier, Reference Number",
                        max_length=20,
                        verbose_name="Receipt Number",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total payment amount made to the supplier",
                        max_digits=12,
                        verbose_name="Total Amount Paid",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date on which payment was made",
                        null=True,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information or remarks about this payment",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="The supplier to whom the payment was made",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier.supplier",
                        verbose_name="Supplier",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment",
                "verbose_name_plural": "Supplier Payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid using this method",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="Optional remarks about this payment method",
                        max_length=50,
                        null=True,
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Method used for the payment (e.g., cash, bank transfer)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.paymentmethod",
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "supplier_payment",
                    models.ForeignKey(
                        help_text="The main payment record this detail belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to="purchase.supplierpayment",
                        verbose_name="Supplier Payment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Payment Detail",
                "verbose_name_plural": "Supplier Payment Details",
            },
        ),
        migrations.CreateModel(
            name="PurchaseDetailSerialNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(max_length=255, verbose_name="Serial Number"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_numbers",
                        to="purchase.purchasedetail",
                        verbose_name="Purchase Detail",
                    ),
                ),
                (
                    "ref_purchase_detail_serial_no",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.purchasedetailserialnumber",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Detail Serial Number",
                "verbose_name_plural": "Purchase Detail Serial Numbers",
                "unique_together": {("serial_no", "purchase_detail")},
            },
        ),
    ]
