# Generated by Django 5.1.4 on 2024-12-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_organizationsetup_about_us_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationsociallink",
            name="social_media",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("TWITTER", "Twitter"),
                    ("LINKEDIN", "Linkedin"),
                    ("INSTAGRAM", "Instagram"),
                    ("YOUTUBE", "Youtube"),
                    ("PINTEREST", "Pinterest"),
                    ("SNAPCHAT", "Snapchat"),
                    ("TIKTOK", "Tiktok"),
                    ("REDDIT", "Reddit"),
                    ("DISCORD", "Discord"),
                    ("TELEGRAM", "Telegram"),
                    ("WHATSAPP", "Whatsapp"),
                    ("SKYPE", "Skype"),
                    ("VIBER", "Viber"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
