from src.base.constants import BaseEnum


class SocialMedias(BaseEnum):
    FACEBOOK = "FACEBOOK"
    TWITTER = "TWITTER"
    LINKEDIN = "LINKEDIN"
    INSTAGRAM = "INSTAGRAM"
    YOUTUBE = "YOUTUBE"
    PINTEREST = "PINTEREST"
    SNAPCHAT = "SNAPCHAT"
    TIKTOK = "TIKTOK"
    REDDIT = "REDDIT"
    DISCORD = "DISCORD"
    TELEGRAM = "TELEGRAM"
    WHATSAPP = "WHATSAPP"
    SKYPE = "SKYPE"
    VIBER = "VIBER"
    OTHER = "OTHER"
