# Generated by Django 5.1.4 on 2025-06-02 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the customer.",
                        max_length=255,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "customer_no",
                    models.CharField(
                        editable=False,
                        help_text="Unique customer number, auto-generated.",
                        max_length=20,
                        unique=True,
                        verbose_name="Customer Number",
                    ),
                ),
                (
                    "is_person",
                    models.BooleanField(
                        default=True,
                        help_text="Is the customer is person or organization/company/group?",
                        verbose_name="Is Person",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the customer (optional).",
                        null=True,
                        upload_to="customer/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email address.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_no",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number.",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "alt_phone_no",
                    models.CharField(
                        blank=True,
                        help_text="Alternative contact number.",
                        max_length=20,
                        verbose_name="Alternative Phone Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or information about the customer.",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("HOME", "Home"),
                            ("OFFICE", "Office"),
                        ],
                        default="DEFAULT",
                        help_text="Optional label like 'Home', 'Office', etc.",
                        max_length=100,
                        verbose_name="Label",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Full Address, e.g. Bhimdatta 10, Kanchanpur, Sudurpashim",
                        max_length=255,
                        verbose_name="Address",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="The customer this address belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customer.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "ordering": ["-id"],
            },
        ),
    ]
