# Generated by Django 5.1.4 on 2025-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("NA", "Na")],
                default="NA",
                help_text="Customer gender in case of person.",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
    ]
