# Generated by Django 5.2 on 2026-10-04 17:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_academiccalendarconfiguration_theme_download_band_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInstitutionProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as deleted. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('singleton_key', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('university_name', models.CharField(max_length=150)),
                ('institute_name', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical institution profile',
                'verbose_name_plural': 'historical institution profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as deleted. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('singleton_key', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=150)),
                ('university_name', models.CharField(max_length=150)),
                ('institute_name', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='historicalprogram',
            name='academic_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='assessment_component',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('COMBINED', 'Combined')], default='THEORY', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='internal_full_marks',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='historicalsubject',
            name='internal_pass_marks',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='program',
            name='academic_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='assessment_component',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('COMBINED', 'Combined')], default='THEORY', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='internal_full_marks',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='subject',
            name='internal_pass_marks',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('internal_full_marks__gte', 1), ('internal_full_marks__lte', 1000)), name='subject_internal_full_marks_range'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('internal_pass_marks__lte', models.F('internal_full_marks'))), name='subject_internal_pass_marks_lte_full'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_component__in', ('THEORY', 'PRACTICAL', 'COMBINED'))), name='subject_assessment_component_valid'),
        ),
        migrations.AddField(
            model_name='historicalinstitutionprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstitutionprofile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstitutionprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Last user to modify this row; empty until the first update.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user to modify this row; empty until the first update.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='institutionprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('singleton_key',), name='one_unarchived_institution_profile', violation_error_message='Edit the existing institution details instead.'),
        ),
        migrations.AddConstraint(
            model_name='institutionprofile',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', True)), name='institution_singleton_key_true'),
        ),
    ]
